apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fakeprod-ca
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: ClusterSecretStore
  - group: '*'
    kind: ClusterIssuer
  description: fakeprod-ca
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
