apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: ClusterSecretStore
  - group: '*'
    kind: ClusterIssuer
  description: staging
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
